### ISSUE TITLE
[SASU-0077] - Xcode 15 Overhaul

### ISSUE THREAD

**Issue by bahaadesso** [adessoTurkey/ios-sample-app-swiftui#84]
**Describe the solution you'd like**
Project should be tested on iOS16 with Xcode 15

**Additional context**
Report the possible problems with iOS 16 and Xcode 15

**Comment by egesucu** [comment]
iOS 17 will be available on the 22nd of September, the branch is ready to be merged when

- the OS is released
- Github provides Xcode 15 on the action runner.
